# Getting the first data set date-2014-04-01-15

## In this step, we have taken the data from 2014-04-01-15 and 2011-03-01-15. Then mwer

In [11]:
# Importing packages

from requests import session
from io import BytesIO
import gzip
import pandas as pd
import numpy as np
import json
import requests
from collections import defaultdict

import os
from pandas.io.json import json_normalize

# declaring the url and output file

url = "https://data.gharchive.org/2014-04-01-15.json.gz"
output_file = "/Users/vinatigattupalli/PycharmProjects/Forks/Cat.json"


# Getting the response of the API
with session() as c:
    response = c.get(url)

    # Loading the content of the response into a file object
    compressed_file = BytesIO(response.content)
    # decompressing the gzip file using gzip
    decompressed_file = gzip.GzipFile(fileobj=compressed_file)


# Writing  the file object into the output file
with open(output_file, 'wb') as handle:
    handle.write(decompressed_file.read())

mylist = []
dict_list = []
with open(output_file, 'r') as handle:
    content = handle.read()
    mylist = content.split("\n")

mylist = list(filter(None, mylist))
for line in mylist:
    dict_list.append(json.loads(str(line)))

df_main = pd.DataFrame()
df_main=pd.io.json.json_normalize(dict_list,sep='_')

#df_main.to_excel('/Users/vinatigattupalli/Documents/Datasets/Dataset1.xlsx',engine='xlsxwriter')

#df.to_csv(r'/Users/vinatigattupalli/Documents/Datasets/Dataset1.csv')

In [12]:
df_main.actor_attributes_name

0                         NaN
1           Sebastian Zartner
2            Philipp Neubauer
3               Matthew Bates
4                      Adrian
                 ...
11690    Luis Ricardo Sanchez
11691              Mat Harden
11692                     NaN
11693                     NaN
11694          Lucian Muresan
Name: actor_attributes_name, Length: 11695, dtype: object

In [13]:
df_main.shape

(11695, 554)

In [14]:
df_main.describe()

,payload_size,repository_id,repository_watchers,repository_stargazers,repository_forks,repository_size,repository_open_issues,payload_comment_id,payload_issue,payload_number,...,payload_repository_forks,payload_repository_open_issues,payload_repository_watchers,payload_membership_id,payload_pull_request_milestone_id,payload_pull_request_milestone_number,payload_pull_request_milestone_creator_id,payload_pull_request_milestone_open_issues,payload_pull_request_milestone_closed_issues,payload_pull_request_head_repo
count,4607.000000,1.151400e+04,11514.000000,11514.000000,11514.000000,1.151400e+04,11514.000000,1.763000e+03,7.050000e+02,1231.000000,...,100.00000,100.000000,100.000000,1.000000e+02,6.000000,6.000000,6.000000e+00,6.000000,6.000000,0.0
mean,12.480573,1.299434e+07,503.373632,503.373632,134.729981,4.154568e+04,29.495397,3.437368e+07,2.976338e+07,841.909017,...,2.38000,0.860000,4.510000,5.615287e+06,413084.500000,10.000000,1.006501e+06,10.000000,149.166667,NaN
std,95.042717,6.126714e+06,2387.499209,2387.499209,827.574980,1.702637e+05,170.141426,1.103331e+07,3.118016e+06,3277.245589,...,14.10622,3.908085,22.095063,3.754217e+02,224982.503904,9.273618,2.111642e+06,11.313708,220.334670,NaN
min,0.000000,2.700000e+01,0.000000,0.000000,0.000000,0.000000e+00,0.000000,5.874314e+06,1.722650e+06,1.000000,...,0.00000,0.000000,0.000000,5.614641e+06,13811.000000,1.000000,9.639600e+04,1.000000,1.000000,NaN
25%,1.000000,8.162615e+06,0.000000,0.000000,0.000000,1.160000e+02,0.000000,3.926664e+07,3.053368e+07,8.000000,...,0.00000,0.000000,1.000000,5.614897e+06,359172.000000,2.750000,1.163558e+05,2.250000,3.500000,NaN
50%,1.000000,1.609966e+07,1.000000,1.000000,0.000000,1.452000e+03,0.000000,3.926877e+07,3.064389e+07,44.000000,...,0.00000,0.000000,1.000000,5.615322e+06,452934.500000,10.000000,1.519290e+05,7.000000,12.000000,NaN
75%,2.000000,1.821819e+07,39.000000,39.000000,16.000000,1.444400e+04,6.000000,3.927026e+07,3.064530e+07,252.500000,...,0.00000,0.000000,1.000000,5.615592e+06,578076.250000,12.000000,2.017058e+05,11.750000,329.500000,NaN
max,1000.000000,1.834807e+07,66275.000000,66275.000000,24915.000000,3.667436e+06,4435.000000,3.927157e+07,3.064644e+07,28058.000000,...,137.00000,31.000000,212.000000,5.615987e+06,611119.000000,26.000000,5.315956e+06,31.000000,434.000000,NaN

## Getting the column names of the first data set

In [15]:
Columnvalues_dataset1=list(df_main)
Dataset_1_columns=pd.DataFrame(Columnvalues_dataset1)
Dataset_1_columns.shape

(554, 1)

In [6]:
#Dataset_1_columns.to_excel('/Users/vinatigattupalli/Documents/ColumnList_Dataset1.xlsx',engine='xlsxwriter')

# Getting the second data set, date-2011-03-01-15

In [7]:
# declaring the url and output file

url_1 = "https://data.gharchive.org/2011-03-01-15.json.gz"
output_file_1 = "/Users/vinatigattupalli/PycharmProjects/Forks/Cat_2.json"


# Getting the response of the API
with session() as c:
    response = c.get(url_1)

    # Loading the content of the response into a file object
    compressed_file = BytesIO(response.content)
    # decompressing the gzip file using gzip
    decompressed_file = gzip.GzipFile(fileobj=compressed_file)


# Writing  the file object into the output file
with open(output_file_1, 'wb') as handle:
    handle.write(decompressed_file.read())

mylist = []
dict_list = []
with open(output_file_1, 'r') as handle:
    content = handle.read()
    mylist = content.split("\n")

mylist = list(filter(None, mylist))
for line in mylist:
    dict_list.append(json.loads(str(line)))




df_main_1 = pd.DataFrame()
df_main_1=pd.io.json.json_normalize(dict_list,sep='_')
#df_main_1.to_excel('/Users/vinatigattupalli/Documents/Datasets/Dataset2.xlsx',engine='xlsxwriter')
#df_main_1.to_csv(r'/Users/vinatigattupalli/Documents/Datasets/Dataset2.csv')

In [8]:
df_main_1.shape

(2406, 56)

In [9]:
df_main_1.head()

,type,public,created_at,id,repo_url,repo_name,payload_ref_type,payload_ref,actor_gravatar_id,actor_id,...,payload_comment_id,payload_commit,payload_issue,payload_forkee,payload_desc,payload_url,payload_snippet,payload_member,payload_original,payload_id
0,DeleteEvent,True,2011-03-01T15:00:00Z,1159594415,https://api.github.dev/repos//,/,branch,SWITCHYARD-84,482d958e5d6c3bea62a14e673febb643,392133.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,PushEvent,True,2011-03-01T15:00:01Z,1159594417,https://api.github.dev/repos/jmertic/KSU_Capst...,jmertic/KSU_Capstone_Spring_2011_PHP,NaN,refs/heads/master,e6e588da9652482949cfe5012bcf1982,606997.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PushEvent,True,2011-03-01T15:00:01Z,1159594420,https://api.github.dev/repos/4poc/feedability,4poc/feedability,NaN,refs/heads/master,556636c6a433b6866bf2445e77f194be,168797.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PushEvent,True,2011-03-01T15:00:02Z,1159594434,https://api.github.dev/repos/landseer/BBCode,landseer/BBCode,NaN,refs/heads/master,23caae53f63ffa43084b7c6ab70a177e,343705.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,PushEvent,True,2011-03-01T15:00:04Z,1159594439,https://api.github.dev/repos/cs0rbagomba/cpp_u...,cs0rbagomba/cpp_utils,NaN,refs/heads/master,2af33e21bf552424bda7cbc50774c9db,640615.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_main_1.describe()

,actor_id,repo_id,payload_size,payload_push_id,payload_target_repos,payload_target_followers,org_id,payload_number,payload_pull_request_number,payload_pull_request_commits,payload_pull_request_deletions,payload_pull_request_id,payload_pull_request_issue_id,payload_pull_request_additions,payload_comment_id,payload_issue,payload_forkee,payload_id
count,2399.000000,2.035000e+03,1252.000000,1.252000e+03,117.000000,117.000000,431.00000,164.000000,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000,33.000000,102.000000,9.200000e+01,11.000000
mean,276611.064193,1.042548e+06,2.882588,2.577840e+07,76.247863,133.376068,314629.74942,55.939024,45.919355,108.338710,4135.596774,79235.516129,621052.483871,7296.290323,287417.212121,607615.637255,1.426528e+06,81622.000000
std,221465.671237,4.279727e+05,16.898241,1.343509e+03,445.762789,315.691216,197721.98506,153.384224,107.071800,579.579297,21857.151834,12155.447010,48504.417161,38072.770176,16.425509,86744.749062,6.766180e+01,3.316625
min,18.000000,1.300000e+02,0.000000,2.577599e+07,0.000000,1.000000,1964.00000,1.000000,1.000000,1.000000,0.000000,30656.000000,426355.000000,0.000000,287395.000000,156215.000000,1.426405e+06,81617.000000
25%,65289.000000,7.516045e+05,1.000000,2.577727e+07,2.000000,2.000000,109777.00000,2.000000,2.000000,1.000000,1.000000,82760.750000,635240.000000,2.000000,287406.000000,635474.500000,1.426478e+06,81619.500000
50%,223003.000000,1.219074e+06,1.000000,2.577841e+07,9.000000,14.000000,314726.00000,7.000000,5.500000,1.000000,2.000000,83403.500000,637645.500000,10.000000,287414.000000,637643.000000,1.426521e+06,81622.000000
75%,479384.000000,1.405103e+06,2.000000,2.577956e+07,16.000000,83.000000,471728.50000,40.500000,32.750000,4.000000,27.750000,83417.750000,637704.250000,99.750000,287426.000000,637698.000000,1.426591e+06,81624.500000
max,645046.000000,1.426653e+06,387.000000,2.578066e+07,3435.000000,1838.000000,759502.00000,1298.000000,497.000000,3257.000000,122843.000000,83441.000000,637781.000000,214032.000000,287455.000000,637779.000000,1.426646e+06,81627.000000

In [11]:
Columnvalues_dataset2=list(df_main_1)
Dataset_2_columns=pd.DataFrame(Columnvalues_dataset2)
Dataset_2_columns.shape

(56, 1)

In [12]:
#Dataset_2_columns.to_excel('/Users/vinatigattupalli/Documents/ColumnList_Dataset2.xlsx',engine='xlsxwriter')

# Merging dataset1 and dataset2

In [10]:
df_final=df_main_1.append(df_main,sort=False)
#df_final.to_excel('/Users/vinatigattupalli/Documents/Datasets/MergedDataset.xlsx',engine='xlsxwriter')
#df_final.to_csv(r'/Users/vinatigattupalli/Documents/Datasets/MergedDataset.csv')

In [14]:
df_final.shape

(14101, 587)

In [15]:
df_final.describe()

,actor_id,repo_id,payload_size,payload_push_id,payload_target_repos,payload_target_followers,org_id,payload_number,payload_pull_request_number,payload_pull_request_commits,...,payload_repository_forks,payload_repository_open_issues,payload_repository_watchers,payload_membership_id,payload_pull_request_milestone_id,payload_pull_request_milestone_number,payload_pull_request_milestone_creator_id,payload_pull_request_milestone_open_issues,payload_pull_request_milestone_closed_issues,payload_pull_request_head_repo
count,2399.000000,2.035000e+03,5859.000000,1.252000e+03,117.000000,117.000000,431.00000,1395.000000,588.000000,588.000000,...,100.00000,100.000000,100.000000,1.000000e+02,6.000000,6.000000,6.000000e+00,6.000000,6.000000,0.0
mean,276611.064193,1.042548e+06,10.429595,2.577840e+07,76.247863,133.376068,314629.74942,749.508244,646.841837,18.352041,...,2.38000,0.860000,4.510000,5.615287e+06,413084.500000,10.000000,1.006501e+06,10.000000,149.166667,NaN
std,221465.671237,4.279727e+05,84.728852,1.343509e+03,445.762789,315.691216,197721.98506,3089.280284,2353.695358,195.050014,...,14.10622,3.908085,22.095063,3.754217e+02,224982.503904,9.273618,2.111642e+06,11.313708,220.334670,NaN
min,18.000000,1.300000e+02,0.000000,2.577599e+07,0.000000,1.000000,1964.00000,1.000000,1.000000,0.000000,...,0.00000,0.000000,0.000000,5.614641e+06,13811.000000,1.000000,9.639600e+04,1.000000,1.000000,NaN
25%,65289.000000,7.516045e+05,1.000000,2.577727e+07,2.000000,2.000000,109777.00000,6.000000,5.000000,1.000000,...,0.00000,0.000000,1.000000,5.614897e+06,359172.000000,2.750000,1.163558e+05,2.250000,3.500000,NaN
50%,223003.000000,1.219074e+06,1.000000,2.577841e+07,9.000000,14.000000,314726.00000,38.000000,35.000000,1.000000,...,0.00000,0.000000,1.000000,5.615322e+06,452934.500000,10.000000,1.519290e+05,7.000000,12.000000,NaN
75%,479384.000000,1.405103e+06,2.000000,2.577956e+07,16.000000,83.000000,471728.50000,213.500000,233.000000,2.000000,...,0.00000,0.000000,1.000000,5.615592e+06,578076.250000,12.000000,2.017058e+05,11.750000,329.500000,NaN
max,645046.000000,1.426653e+06,1000.000000,2.578066e+07,3435.000000,1838.000000,759502.00000,28058.000000,28057.000000,3257.000000,...,137.00000,31.000000,212.000000,5.615987e+06,611119.000000,26.000000,5.315956e+06,31.000000,434.000000,NaN

In [16]:
Column_Values=list(df_final)

In [17]:
df_columns=pd.DataFrame(Column_Values)

In [18]:
df_columns.shape

(587, 1)

In [19]:
#df_columns.to_excel('/Users/vinatigattupalli/Documents/ColumnList.xlsx',engine='xlsxwriter')

In [20]:
df_final.actor_attributes_name

0                         NaN
1                         NaN
2                         NaN
3                         NaN
4                         NaN
                 ...
11690    Luis Ricardo Sanchez
11691              Mat Harden
11692                     NaN
11693                     NaN
11694          Lucian Muresan
Name: actor_attributes_name, Length: 14101, dtype: object